# Generated by Django 5.1.6 on 2025-03-14 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GeneratedResume', '0007_delete_resumeevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('match_percentage', models.FloatField()),
                ('missing_keywords', models.JSONField(default=list)),
                ('improvement_tips', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='GeneratedResume.resume')),
            ],
        ),
    ]
