# Generated by Django 5.1.6 on 2025-03-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeneratedResume', '0006_resumeevaluation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumeEvaluation',
        ),
    ]
