# Generated by Django 5.1.6 on 2025-03-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneratedResume', '0007_delete_resumeevaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='linkedin_link',
        ),
        migrations.AddField(
            model_name='resume',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
