# Generated by Django 5.1.6 on 2025-03-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneratedResume', '0011_alter_user_email_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
