# Generated by Django 5.0.3 on 2025-03-19 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RecommendationJob', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='RecommendationJob.job')),
            ],
        ),
    ]
