# Generated by Django 5.1.6 on 2025-03-17 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeneratedQuestion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenerateQuestion',
        ),
    ]
