# Generated by Django 5.1.6 on 2025-03-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecommendationJob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_required',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
