# Generated by Django 5.1.6 on 2025-03-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecommendationJob', '0002_alter_job_experience_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_required',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
